---
- name: Install vars
  hosts: all
  become: yes
  vars:
      owner: axlial
      email: axlial@mail.ru

  tasks:

  - name: Print var owner
    debug:
         var: owner
  - name: Save from var
    shell: uptime
    register: up
  - debug: 
         var: up.stdout
